/**
 * The live campaign telemetry contract: a closed union of typed delta frames.
 *
 * This is the proposed wire projection described in
 * `docs/design/live-campaign-streaming.md`. Each frame is a small delta; folding
 * the stream in order reconstructs a `CampaignRecord`. The frames are the single
 * boundary between an untrusted source (a dev replay server today, the
 * orchestrator's projection later) and the typed client state.
 *
 * `parseCampaignFrame` validates once, here. Everything downstream (the fold and
 * the view) consumes typed values and never re-validates.
 */
import type {CampaignRecord, WorkstreamOutcome} from './campaign-record.js';

/** Mirrors the backend `WorkstreamPhase` StrEnum. A hand-written copy until the
 * backend emits these frames and the union is generated by `pnpm
 * generate:protocol`; see the design doc's "Backend path". */
export type WorkstreamPhase =
  | 'pending'
  | 'implementing'
  | 'implemented'
  | 'reviewed'
  | 'evaluated'
  | 'failed'
  | 'parked'
  | 'cancelled';

const WORKSTREAM_PHASES: readonly WorkstreamPhase[] = [
  'pending',
  'implementing',
  'implemented',
  'reviewed',
  'evaluated',
  'failed',
  'parked',
  'cancelled',
];

/** The campaign-level data known at (or declared for) the start of a run. */
export type CampaignHeader = Pick<
  CampaignRecord,
  | 'id'
  | 'title'
  | 'summary'
  | 'provenance'
  | 'objective'
  | 'benchmarkVersions'
  | 'benchmarkVersionBoundary'
  | 'trajectories'
>;

export type FrameAgent = CampaignRecord['agents'][number];
export type FrameMeasurement = CampaignRecord['measurements'][number];

/**
 * A workstream delta. Unlike the finished-record shape, a live workstream may be
 * in flight: `active` is true, and `finishedAt`/`outcome`/`lastSequence` are not
 * known yet. The fold stores the phase; the view model projects an active
 * workstream's end to "now" so the existing dashboard renders it as active.
 */
export interface FrameWorkstream {
  readonly id: string;
  readonly title: string;
  readonly hypothesis: string;
  readonly startedAt: string;
  readonly firstSequence: number;
  readonly phase: WorkstreamPhase;
  readonly active: boolean;
  readonly finishedAt: string | null;
  readonly lastSequence: number | null;
  readonly outcome: WorkstreamOutcome | null;
  readonly outcomeSummary: string;
}

export type CampaignFrame =
  | {readonly kind: 'campaign-init'; readonly seq: number; readonly header: CampaignHeader}
  | {readonly kind: 'agent-upsert'; readonly seq: number; readonly agent: FrameAgent}
  | {readonly kind: 'workstream-upsert'; readonly seq: number; readonly workstream: FrameWorkstream}
  | {readonly kind: 'measurement'; readonly seq: number; readonly measurement: FrameMeasurement}
  | {
      readonly kind: 'tokens';
      readonly seq: number;
      readonly workstreamId: string;
      readonly tokens: number;
    }
  | {readonly kind: 'status'; readonly seq: number; readonly status: 'active' | 'completed'};

type CampaignFrameKind = CampaignFrame['kind'];

const FRAME_KINDS: readonly CampaignFrameKind[] = [
  'campaign-init',
  'agent-upsert',
  'workstream-upsert',
  'measurement',
  'tokens',
  'status',
];

class FrameError extends Error {}

function fail(path: string, message: string): never {
  throw new FrameError(`${path}: ${message}`);
}

/**
 * A parsed object with the frame fields declared, so property access reads as
 * `object.kind` rather than an index-signature lookup. Mirrors the `JsonObject`
 * approach in `replay-scenario.ts`.
 */
type FrameObject = Record<string, unknown> & {
  kind?: unknown;
  seq?: unknown;
  header?: unknown;
  agent?: unknown;
  workstream?: unknown;
  measurement?: unknown;
  workstreamId?: unknown;
  tokens?: unknown;
  status?: unknown;
  id?: unknown;
  title?: unknown;
  hypothesis?: unknown;
  startedAt?: unknown;
  firstSequence?: unknown;
  phase?: unknown;
  active?: unknown;
  finishedAt?: unknown;
  lastSequence?: unknown;
  outcome?: unknown;
  outcomeSummary?: unknown;
};

function asObject(value: unknown, path: string): FrameObject {
  if (typeof value !== 'object' || value === null || Array.isArray(value))
    fail(path, 'expected an object');
  return value as FrameObject;
}

function asString(value: unknown, path: string): string {
  if (typeof value !== 'string') fail(path, 'expected a string');
  return value;
}

function asNumber(value: unknown, path: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) fail(path, 'expected a finite number');
  return value;
}

function asBoolean(value: unknown, path: string): boolean {
  if (typeof value !== 'boolean') fail(path, 'expected a boolean');
  return value;
}

function member<T extends string>(value: unknown, path: string, allowed: readonly T[]): T {
  const text = asString(value, path);
  if (!allowed.includes(text as T)) fail(path, `expected one of ${allowed.join(', ')}`);
  return text as T;
}

function exactKeys(object: FrameObject, path: string, keys: readonly string[]): void {
  for (const key of Object.keys(object))
    if (!keys.includes(key)) fail(`${path}.${key}`, 'unexpected key');
  for (const key of keys) if (!(key in object)) fail(`${path}.${key}`, 'missing key');
}

function nullableString(value: unknown, path: string): string | null {
  return value === null ? null : asString(value, path);
}

function nullableNumber(value: unknown, path: string): number | null {
  return value === null ? null : asNumber(value, path);
}

function parseWorkstream(value: unknown, path: string): FrameWorkstream {
  const object = asObject(value, path);
  exactKeys(object, path, [
    'id',
    'title',
    'hypothesis',
    'startedAt',
    'firstSequence',
    'phase',
    'active',
    'finishedAt',
    'lastSequence',
    'outcome',
    'outcomeSummary',
  ]);
  return {
    id: asString(object.id, `${path}.id`),
    title: asString(object.title, `${path}.title`),
    hypothesis: asString(object.hypothesis, `${path}.hypothesis`),
    startedAt: asString(object.startedAt, `${path}.startedAt`),
    firstSequence: asNumber(object.firstSequence, `${path}.firstSequence`),
    phase: member(object.phase, `${path}.phase`, WORKSTREAM_PHASES),
    active: asBoolean(object.active, `${path}.active`),
    finishedAt: nullableString(object.finishedAt, `${path}.finishedAt`),
    lastSequence: nullableNumber(object.lastSequence, `${path}.lastSequence`),
    outcome:
      object.outcome === null
        ? null
        : member(object.outcome, `${path}.outcome`, ['accepted', 'rejected'] as const),
    outcomeSummary: asString(object.outcomeSummary, `${path}.outcomeSummary`),
  };
}

/**
 * Validate an unknown value as a campaign frame, rejecting an unknown kind,
 * an unexpected or missing key, or a wrong type, and naming the offending path.
 * The payloads that are `CampaignRecord` sub-objects (`header`, `agent`,
 * `measurement`) are carried as-is and checked structurally at the top level;
 * the producer is the record validated by `parseReplayScenario`.
 */
export function parseCampaignFrame(value: unknown): CampaignFrame {
  const object = asObject(value, '$');
  const kind = member(object.kind, '$.kind', FRAME_KINDS);
  const seq = asNumber(object.seq, '$.seq');
  switch (kind) {
    case 'campaign-init': {
      exactKeys(object, '$', ['kind', 'seq', 'header']);
      return {kind, seq, header: asObject(object.header, '$.header') as unknown as CampaignHeader};
    }
    case 'agent-upsert': {
      exactKeys(object, '$', ['kind', 'seq', 'agent']);
      return {kind, seq, agent: asObject(object.agent, '$.agent') as unknown as FrameAgent};
    }
    case 'workstream-upsert': {
      exactKeys(object, '$', ['kind', 'seq', 'workstream']);
      return {kind, seq, workstream: parseWorkstream(object.workstream, '$.workstream')};
    }
    case 'measurement': {
      exactKeys(object, '$', ['kind', 'seq', 'measurement']);
      return {
        kind,
        seq,
        measurement: asObject(object.measurement, '$.measurement') as unknown as FrameMeasurement,
      };
    }
    case 'tokens': {
      exactKeys(object, '$', ['kind', 'seq', 'workstreamId', 'tokens']);
      return {
        kind,
        seq,
        workstreamId: asString(object.workstreamId, '$.workstreamId'),
        tokens: asNumber(object.tokens, '$.tokens'),
      };
    }
    case 'status': {
      exactKeys(object, '$', ['kind', 'seq', 'status']);
      return {
        kind,
        seq,
        status: member(object.status, '$.status', ['active', 'completed'] as const),
      };
    }
  }
}

export function isTerminalPhase(phase: WorkstreamPhase): boolean {
  return phase === 'evaluated' || phase === 'failed' || phase === 'cancelled';
}
