apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-config-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-config-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-mongo
spec:
  selector:
    app: ts-config-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-station-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-station-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-mongo
spec:
  selector:
    app: ts-station-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-train-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-train-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-train-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-mongo
spec:
  selector:
    app: ts-train-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-travel-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-travel-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-mongo
spec:
  selector:
    app: ts-travel-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-route-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-route-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-route-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-mongo
spec:
  selector:
    app: ts-route-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-mongo
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-price-mongo
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-price-mongo
        image: mongo:3.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        readinessProbe:
          tcpSocket:
            port: 27017
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-price-mongo
spec:
  selector:
    app: ts-price-mongo
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-config-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-config-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-config-service
        image: vibesys-config-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 15679
        readinessProbe:
          httpGet:
            path: /api/v1/configservice/welcome
            port: 15679
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-config-service
spec:
  selector:
    app: ts-config-service
  ports:
  - port: 15679
    targetPort: 15679
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-station-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-station-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-station-service
        image: vibesys-station-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12345
        readinessProbe:
          httpGet:
            path: /api/v1/stationservice/welcome
            port: 12345
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-station-service
spec:
  selector:
    app: ts-station-service
  ports:
  - port: 12345
    targetPort: 12345
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-train-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-train-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-train-service
        image: vibesys-train-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 14567
        readinessProbe:
          httpGet:
            path: /api/v1/trainservice/trains/welcome
            port: 14567
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-train-service
spec:
  selector:
    app: ts-train-service
  ports:
  - port: 14567
    targetPort: 14567
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-travel-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-travel-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-travel-service
        image: vibesys-travel-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 12346
        readinessProbe:
          httpGet:
            path: /api/v1/travelservice/welcome
            port: 12346
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-travel-service
spec:
  selector:
    app: ts-travel-service
  ports:
  - port: 12346
    targetPort: 12346
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-route-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-route-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-route-service
        image: vibesys-route-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 11178
        readinessProbe:
          httpGet:
            path: /api/v1/routeservice/welcome
            port: 11178
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-route-service
spec:
  selector:
    app: ts-route-service
  ports:
  - port: 11178
    targetPort: 11178
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-price-service
spec:
  replicas: 1
  selector:
    matchLabels: &id001
      app: ts-price-service
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: ts-price-service
        image: vibesys-price-${NAMESPACE}:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 16579
        readinessProbe:
          httpGet:
            path: /api/v1/priceservice/prices/welcome
            port: 16579
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 450
---
apiVersion: v1
kind: Service
metadata:
  name: ts-price-service
spec:
  selector:
    app: ts-price-service
  ports:
  - port: 16579
    targetPort: 16579
