# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server/wire/v2/server_messages.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'server/wire/v2/server_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from server.wire.v2 import common_pb2 as server_dot_wire_dot_v2_dot_common__pb2
from server.wire.v2 import events_pb2 as server_dot_wire_dot_v2_dot_events__pb2
from server.wire.v2 import snapshot_pb2 as server_dot_wire_dot_v2_dot_snapshot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$server/wire/v2/server_messages.proto\x12\x0eserver.wire.v2\x1a\x1bserver/wire/v2/common.proto\x1a\x1bserver/wire/v2/events.proto\x1a\x1dserver/wire/v2/snapshot.proto\"r\n\x11SubscribedMessage\x12\x1d\n\nrequest_id\x18\x01 \x01(\tR\trequestId\x12\x15\n\x06run_id\x18\x02 \x01(\tR\x05runId\x12\'\n\x0flatest_sequence\x18\x03 \x01(\rR\x0elatestSequence\"\x94\x02\n\x11\x45ventBatchMessage\x12\x30\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x18.server.wire.v2.RunEventR\x06\x65vents\x12)\n\x10through_sequence\x18\x02 \x01(\rR\x0fthroughSequence\x12Q\n\x11\x61\x63tive_executions\x18\x03 \x03(\x0b\x32$.server.wire.v2.ActiveAgentExecutionR\x10\x61\x63tiveExecutions\x12\x19\n\x08store_id\x18\x04 \x01(\tR\x07storeId\x12\x34\n\x16history_after_sequence\x18\x05 \x01(\rR\x14historyAfterSequence\"\xc7\x01\n\x14ProtocolErrorMessage\x12\"\n\nrequest_id\x18\x01 \x01(\tH\x00R\trequestId\x88\x01\x01\x12\x12\n\x04\x63ode\x18\x02 \x01(\tR\x04\x63ode\x12\x18\n\x07message\x18\x03 \x01(\tR\x07message\x12?\n\ndiagnostic\x18\x04 \x01(\x0b\x32\x1a.server.wire.v2.DiagnosticH\x01R\ndiagnostic\x88\x01\x01\x42\r\n\x0b_request_idB\r\n\x0b_diagnostic\"\xa3\x02\n\rServerMessage\x12\x43\n\nsubscribed\x18\x01 \x01(\x0b\x32!.server.wire.v2.SubscribedMessageH\x00R\nsubscribed\x12\x30\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x18.server.wire.v2.RunEventH\x00R\x05\x65vent\x12\x44\n\x0b\x65vent_batch\x18\x03 \x01(\x0b\x32!.server.wire.v2.EventBatchMessageH\x00R\neventBatch\x12M\n\x0eprotocol_error\x18\x04 \x01(\x0b\x32$.server.wire.v2.ProtocolErrorMessageH\x00R\rprotocolErrorB\x06\n\x04\x62odyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server.wire.v2.server_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBEDMESSAGE']._serialized_start=145
  _globals['_SUBSCRIBEDMESSAGE']._serialized_end=259
  _globals['_EVENTBATCHMESSAGE']._serialized_start=262
  _globals['_EVENTBATCHMESSAGE']._serialized_end=538
  _globals['_PROTOCOLERRORMESSAGE']._serialized_start=541
  _globals['_PROTOCOLERRORMESSAGE']._serialized_end=740
  _globals['_SERVERMESSAGE']._serialized_start=743
  _globals['_SERVERMESSAGE']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
