"""Versioned evaluator package contracts and local resolution."""

from vibesys.evaluators.packages import (
    PACKAGE_ROOT_TOKEN,
    PROJECT_ROOT_TOKEN,
    PYTHON_TOKEN,
    TOOL_TOKEN_PREFIX,
    EvaluatorPackageError,
    EvaluatorPackageMetadata,
    EvaluatorPackageNotFoundError,
    EvaluatorPackageRegistry,
    EvaluatorPackageRequirement,
    ResolvedEvaluatorPackage,
    load_evaluator_package,
    resolve_evaluator_package,
)
from vs_sandbox.api.evaluator_tools import (
    CargoGitToolSpec,
    EvaluatorToolError,
    EvaluatorToolLifecycleHooks,
    cargo_install_argv,
    evaluator_tools_install_command,
    prepare_evaluator_tools,
    tool_install_root,
    tool_path_replacements,
    tool_spec_digest,
    tool_token,
)

__all__ = [
    "PACKAGE_ROOT_TOKEN",
    "PROJECT_ROOT_TOKEN",
    "PYTHON_TOKEN",
    "TOOL_TOKEN_PREFIX",
    "CargoGitToolSpec",
    "EvaluatorPackageError",
    "EvaluatorPackageMetadata",
    "EvaluatorPackageNotFoundError",
    "EvaluatorPackageRegistry",
    "EvaluatorPackageRequirement",
    "EvaluatorToolError",
    "EvaluatorToolLifecycleHooks",
    "ResolvedEvaluatorPackage",
    "cargo_install_argv",
    "evaluator_tools_install_command",
    "load_evaluator_package",
    "prepare_evaluator_tools",
    "resolve_evaluator_package",
    "tool_install_root",
    "tool_path_replacements",
    "tool_spec_digest",
    "tool_token",
]
