import {fileURLToPath} from 'node:url';
import type {KnipConfig} from 'knip';
import {workspaceLayout} from './scripts/workspace_layout.mjs';

type WorkspacePolicy = NonNullable<KnipConfig['workspaces']>[string];

// What knip audits inside each package. The keys are checked against the workspace layout below,
// not maintained here: a package that joins the workspace without a policy fails this gate by
// name instead of silently falling back to knip's default entry-point heuristics, which is how
// `web` came to be audited against defaults meant for a library rather than a bundled app.
const PACKAGE_POLICIES: Record<string, WorkspacePolicy> = {
  'backend-client': {
    entry: ['src/**/*.test.ts'],
    project: ['src/**/*.ts'],
    // Generated by `pnpm generate:protocol` (json2ts): every schema definition is exported
    // whether or not the TUI uses it, and the file must not be edited by hand.
    ignore: ['src/generated/**'],
  },
  'core-state': {
    entry: ['src/**/*.test.ts', 'bench/*.ts'],
    project: ['src/**/*.ts', 'bench/**/*.ts'],
  },
  tui: {
    entry: [
      // The frontend process: the launcher (the `bin`, an entry by default) spawns `dist/index.js`.
      'src/index.ts',
      'src/**/*.test.ts',
      // Replay harness: `mock-ui.sh` starts `mock-server.ts`; `harness.test.ts` runs under `bun test`.
      'dev/mock-server.ts',
      'dev/**/*.test.ts',
      // Hand-run benchmark (`bun benchmarks/experiment-refresh.ts`).
      'benchmarks/*.ts',
    ],
    project: ['src/**/*.ts', 'dev/**/*.ts', 'benchmarks/**/*.ts'],
  },
  web: {
    entry: [
      // The package's public surface (`@vibesys/web`), which the browser bundle and the
      // end-to-end specs import; `vite.config.ts` and `index.html` supply the app entries.
      'src/index.ts',
      'src/**/*.test.ts',
      'src/**/*.test.tsx',
      // Playwright specs, run by `pnpm --filter @vibesys/web test:e2e`.
      'e2e/**/*.spec.ts',
      // The harness's own public surface: specs use only part of it.
      'e2e/gateway.ts',
      'e2e/home.ts',
    ],
    project: ['src/**/*.ts', 'src/**/*.tsx', 'e2e/**/*.ts'],
  },
  desktop: {
    // The electron-vite plugin finds the config and its two process entries; Playwright's
    // finds playwright.config.ts and e2e/*.spec.ts. Knip follows `home.test.ts`'s
    // `new URL('../../test/fake-home.ts', import.meta.url)` to the fake home on its own.
    entry: ['src/**/*.test.ts'],
    project: ['src/**/*.ts', 'test/**/*.ts', 'e2e/**/*.ts'],
  },
};

// Repository tooling run by `node scripts/...`; `*.test.mjs` runs under `node --test`. The
// workspace root is not a package, so it is not part of the derived set.
const ROOT_POLICY: WorkspacePolicy = {
  entry: ['scripts/*.mjs'],
  project: ['scripts/**/*.mjs'],
};

const layout = workspaceLayout(fileURLToPath(new URL('.', import.meta.url)));

const workspaces: Record<string, WorkspacePolicy> = {'.': ROOT_POLICY};
for (const {name, directory} of layout.packages) {
  const policy = PACKAGE_POLICIES[directory];
  if (policy === undefined) {
    throw new Error(`knip.config.ts: ${name} (${directory}/) has no entry or project policy`);
  }
  workspaces[directory] = policy;
}

const config: KnipConfig = {
  // External programs run by scripts or tests, not npm packages: `uv` (generate:protocol, dev
  // machines only) and `pkill` (harness.test.ts cleanup).
  ignoreBinaries: ['uv', 'pkill'],
  workspaces,
};

export default config;
