"""Stable VibeSys framework surface for generic run and mechanism contracts.

VibeSys implementations import framework-owned contracts and foundational
mechanism APIs here. The implementation and backing libraries remain private
to this package boundary.
"""

from __future__ import annotations

from framework.agent_sessions import SynchronizedSessionStore
from framework.run_view import RoundSummary, RunResult, RunStatus, RunView
from vs_agent.api import (
    CLI_VERSIONS,
    DEFAULT_CLI_PROVIDER,
    DOCKER_PROVIDER_ENV,
    GO_TOOLCHAIN_VERSION,
    NODE_VERSION,
    NULL_SKILL_SELECTION,
    RUST_TOOLCHAIN_VERSION,
    AgentBackend,
    AgentCapabilities,
    AgentClientProtocol,
    AgentExecutionPolicy,
    AgentOutputChannel,
    AgentProgress,
    AgentSessionKey,
    AgentSessionState,
    AgentSpec,
    AgentStatusData,
    CandidateProgress,
    CommandResultPayload,
    Driver,
    DurableSessionStore,
    JsonResultPayload,
    MCPServerSpec,
    RoundProgress,
    SessionScope,
    SkillSelection,
    StdioServerDescriptor,
    TodoItemData,
    ToolResultPayload,
    ToolSpec,
    agent_driver_supports_mcp_servers,
    auth_bind_mounts,
    auth_copy_paths,
    auth_env_passthrough,
    auth_env_vars,
    auth_paths,
    build_agent_client,
    cli_skill_dirs,
    expose_as_tools,
    serve_stdio,
    task_agent_host_resources,
)
from vs_agent.api.testing import AgentResponseContext
from vs_evaluator_protocol.api import (
    Hello,
    ProtocolError,
    check_objectives,
    parse_records,
    read_measurement,
)
from vs_project.api import (
    FrameworkSnapshotStatus,
    GitTracker,
    GitTrackerEvents,
    NullGitTrackerEvents,
    OrchestrationDescriptor,
    OrchestrationRunManifest,
    Project,
    ProjectStateError,
    RunEnvironmentRecord,
    RunExecutionRecord,
    RunLogger,
    RunResourceRequest,
    StateNamespace,
    StateSlot,
    StateSnapshot,
    TaskDirectory,
    generate_run_id,
    is_project_state_path,
    strip_ansi,
    validate_socket_path,
)
from vs_sandbox.api import (
    AGENT_HOME,
    BeforeReadyContext,
    DockerSandbox,
    HostResource,
    HostResourceAccess,
    LocalShellSandbox,
    ProjectPathPolicy,
    Sandbox,
    SandboxExecutionResult,
    SandboxLifecycle,
    SandboxLifecycleHooks,
    ensure_model_volume,
)
from vs_sandbox.api.testing import FakeSandbox

__all__ = [
    "AGENT_HOME",
    "CLI_VERSIONS",
    "DEFAULT_CLI_PROVIDER",
    "DOCKER_PROVIDER_ENV",
    "GO_TOOLCHAIN_VERSION",
    "NODE_VERSION",
    "NULL_SKILL_SELECTION",
    "RUST_TOOLCHAIN_VERSION",
    "AgentBackend",
    "AgentCapabilities",
    "AgentClientProtocol",
    "AgentExecutionPolicy",
    "AgentOutputChannel",
    "AgentProgress",
    "AgentResponseContext",
    "AgentSessionKey",
    "AgentSessionState",
    "AgentSpec",
    "AgentStatusData",
    "BeforeReadyContext",
    "CandidateProgress",
    "CommandResultPayload",
    "DockerSandbox",
    "Driver",
    "DurableSessionStore",
    "FakeSandbox",
    "FrameworkSnapshotStatus",
    "GitTracker",
    "GitTrackerEvents",
    "Hello",
    "HostResource",
    "HostResourceAccess",
    "JsonResultPayload",
    "LocalShellSandbox",
    "MCPServerSpec",
    "NullGitTrackerEvents",
    "OrchestrationDescriptor",
    "OrchestrationRunManifest",
    "Project",
    "ProjectPathPolicy",
    "ProjectStateError",
    "ProtocolError",
    "RoundProgress",
    "RoundSummary",
    "RunEnvironmentRecord",
    "RunExecutionRecord",
    "RunLogger",
    "RunResourceRequest",
    "RunResult",
    "RunStatus",
    "RunView",
    "Sandbox",
    "SandboxExecutionResult",
    "SandboxLifecycle",
    "SandboxLifecycleHooks",
    "SessionScope",
    "SkillSelection",
    "StateNamespace",
    "StateSlot",
    "StateSnapshot",
    "StdioServerDescriptor",
    "SynchronizedSessionStore",
    "TaskDirectory",
    "TodoItemData",
    "ToolResultPayload",
    "ToolSpec",
    "agent_driver_supports_mcp_servers",
    "auth_bind_mounts",
    "auth_copy_paths",
    "auth_env_passthrough",
    "auth_env_vars",
    "auth_paths",
    "build_agent_client",
    "check_objectives",
    "cli_skill_dirs",
    "ensure_model_volume",
    "expose_as_tools",
    "generate_run_id",
    "is_project_state_path",
    "parse_records",
    "read_measurement",
    "serve_stdio",
    "strip_ansi",
    "task_agent_host_resources",
    "validate_socket_path",
]
