"""Public contracts and implementation for the SkyPilot sandbox backend.

VibeSys selects and composes this backend, while this module owns cluster
profile validation, CLI lifecycle, the evaluator bridge protocol, and durable
invocation recovery.  Importing the general :mod:`vs_sandbox.api` facade does
not load these optional backend details.
"""

from vs_sandbox.skypilot_bridge import SkyPilotBridge
from vs_sandbox.skypilot_config import (
    ClusterProfileError,
    ClusterProfilesFile,
    ResolvedSkyPilotResources,
    SkyPilotProfile,
    load_cluster_profiles,
    resolve_profile,
)
from vs_sandbox.skypilot_protocol import (
    PROTOCOL_VERSION,
    AckedFrame,
    AckRequest,
    ArtifactFrame,
    ErrorFrame,
    EvaluationRequest,
    OutputFrame,
    ResponseFrame,
    ResultFrame,
    compact_json,
    decode_ack,
    decode_request,
    decode_response,
    encode_message,
)
from vs_sandbox.skypilot_recovery import (
    ArtifactRecord,
    AttemptResourcesRecord,
    InvocationJournal,
    InvocationPhase,
    InvocationProvenance,
    InvocationRecord,
    InvocationResultRecord,
    deterministic_job_name,
)
from vs_sandbox.skypilot_runner import (
    ClusterInfo,
    ClusterStatus,
    CommandRunner,
    JobResult,
    JobStatus,
    ProcessResult,
    RemoteJobInfo,
    RemoteJobStatus,
    SkyPilotCLIError,
    SkyPilotClusterNotReadyError,
    SkyPilotControlPlaneError,
    SkyPilotJobRunner,
    SkyPilotJobStateError,
    SkyPilotOutputError,
    SkyPilotTimeoutError,
    SubprocessCommandRunner,
    build_task_document,
    stable_cluster_name,
)

__all__ = [
    "PROTOCOL_VERSION",
    "AckRequest",
    "AckedFrame",
    "ArtifactFrame",
    "ArtifactRecord",
    "AttemptResourcesRecord",
    "ClusterInfo",
    "ClusterProfileError",
    "ClusterProfilesFile",
    "ClusterStatus",
    "CommandRunner",
    "ErrorFrame",
    "EvaluationRequest",
    "InvocationJournal",
    "InvocationPhase",
    "InvocationProvenance",
    "InvocationRecord",
    "InvocationResultRecord",
    "JobResult",
    "JobStatus",
    "OutputFrame",
    "ProcessResult",
    "RemoteJobInfo",
    "RemoteJobStatus",
    "ResolvedSkyPilotResources",
    "ResponseFrame",
    "ResultFrame",
    "SkyPilotBridge",
    "SkyPilotCLIError",
    "SkyPilotClusterNotReadyError",
    "SkyPilotControlPlaneError",
    "SkyPilotJobRunner",
    "SkyPilotJobStateError",
    "SkyPilotOutputError",
    "SkyPilotProfile",
    "SkyPilotTimeoutError",
    "SubprocessCommandRunner",
    "build_task_document",
    "compact_json",
    "decode_ack",
    "decode_request",
    "decode_response",
    "deterministic_job_name",
    "encode_message",
    "load_cluster_profiles",
    "resolve_profile",
    "stable_cluster_name",
]
