"""Published proof fact contract for reducer consumers and public properties."""

from vs_core._proofs import (
    Mismatch,
    Missing,
    ProofField,
    ProofReason,
    Proven,
    Verdict,
    accepted_receipt_for,
    committed_stop,
    current_admission,
    current_closure,
    dependencies_for,
    descriptor_matches,
    fresh_observation,
    invocation_for,
    nonempty_required,
    observation_for,
    operation_for,
    released_owner,
    request_matches,
    resolved_observation,
    submission_budget_for,
)

__all__ = [
    "Mismatch",
    "Missing",
    "ProofField",
    "ProofReason",
    "Proven",
    "Verdict",
    "accepted_receipt_for",
    "committed_stop",
    "current_admission",
    "current_closure",
    "dependencies_for",
    "descriptor_matches",
    "fresh_observation",
    "invocation_for",
    "nonempty_required",
    "observation_for",
    "operation_for",
    "released_owner",
    "request_matches",
    "resolved_observation",
    "submission_budget_for",
]
