"""Core runtime composition surface. No legacy loop or concrete I/O binding.

Start validates schema/declarations and persists new-epoch recovery. Inputs and
observations enter one queue; only confirmed commits authorize dispatch or
publication. Unbound executor roles return named typed refusals.
"""

from vs_runtime._core_loop import (
    CoreContractGapError,
    CoreRuntime,
    CoreRuntimeBindings,
    CoreTransitions,
    DispatchProgress,
    ObservationRejectedError,
    OwnerEventRejectedError,
    ProductionCoreTransitions,
    PublicationDelivery,
    RuntimeCommitError,
    RuntimeCommitUncertainError,
    RuntimeExecutionError,
)
from vs_runtime._core_preflight import (
    CoreResumeError,
    ResolvedCoreResume,
    ResumeDiagnostic,
    resolve_core_resume,
)
from vs_runtime._core_publications import JournalPublicationDelivery
from vs_runtime._core_record import (
    RUNTIME_SCHEMA_VERSION,
    Publication,
    PublicationAcknowledgement,
    PublicationContext,
    PublicationHistory,
    RuntimeRecord,
)
from vs_runtime._core_requests import (
    REQUEST_DISPATCH,
    EvaluationRequests,
    ExecutionContext,
    ExecutionLease,
    ExecutionOutcome,
    ExecutionResult,
    ExecutorRefusal,
    ExecutorRole,
    OperationExecutor,
    OwnerEvent,
    RefusingRequestExecution,
    RequestExecutors,
    SemanticEvents,
    SessionRequests,
    WorkspaceRequests,
    receipt_executor_kinds,
)
from vs_runtime._evaluation_requests import JobRecord, MeasurementRequests
from vs_runtime._evidence_ledger import (
    EvidenceEntry,
    EvidenceLookup,
    EvidenceRecorder,
    ReceiptEvidenceLedger,
)
from vs_runtime._evidence_operations import InterpretEvidenceOwner, RetainRevisionOwner
from vs_runtime._observation_factory import (
    ObservationFactory,
    ObservationFacts,
    ObservationLedgerCorruptError,
    ObservationSubject,
)
from vs_runtime._operation_catalog import (
    Applied,
    CancellableOwner,
    Cancelled,
    Indeterminate,
    Inspection,
    NotApplied,
    OperationCatalog,
    OperationEntry,
    OperationOwner,
    RefusalReason,
)
from vs_runtime._operation_receipts import (
    IntentReceipt,
    NamespaceOperationReceipts,
    OperationReceipts,
    ResultReceipt,
)
from vs_runtime._operation_requests import RegisteredOperationRequests
from vs_runtime._operation_wiring import (
    OperationPorts,
    OperationRole,
    bind_operations,
    build_operation_catalog,
    production_owners,
)
from vs_runtime._receipt_store import (
    Conflict,
    Declined,
    Performed,
    Performer,
    ReceiptCorruptError,
    ReceiptStore,
    Replayed,
    Settled,
    Transient,
    owner_key,
)
from vs_runtime._render_operation import RenderArtifactsOwner
from vs_runtime._semantic_events import BlockDiagnostic, JournalSemanticEvents
from vs_runtime._session_lifecycle_requests import (
    ContinuationBinding,
    ReleasedRunInvocations,
    SessionLifecycleRequests,
    SessionRequestRouter,
    TurnDispatcher,
)
from vs_runtime._session_requests import (
    JournalRunInvocations,
    RuntimeSessionRequests,
    SessionBinding,
    SessionResolver,
)
from vs_runtime._verify_revision_operation import VerifyRevisionOwner
from vs_runtime._workspace_receipts import (
    AttemptBinding,
    RootGrant,
    StoreWorkspaceReceipts,
    WorkspaceReceipts,
)
from vs_runtime._workspace_requests import (
    RunInvocationProof,
    RuntimeWorkspaceRequests,
    commit_of,
    revision_ref,
)

__all__ = [
    "REQUEST_DISPATCH",
    "RUNTIME_SCHEMA_VERSION",
    "Applied",
    "AttemptBinding",
    "BlockDiagnostic",
    "CancellableOwner",
    "Cancelled",
    "Conflict",
    "ContinuationBinding",
    "CoreContractGapError",
    "CoreResumeError",
    "CoreRuntime",
    "CoreRuntimeBindings",
    "CoreTransitions",
    "Declined",
    "DispatchProgress",
    "EvaluationRequests",
    "EvidenceEntry",
    "EvidenceLookup",
    "EvidenceRecorder",
    "ExecutionContext",
    "ExecutionLease",
    "ExecutionOutcome",
    "ExecutionResult",
    "ExecutorRefusal",
    "ExecutorRole",
    "Indeterminate",
    "Inspection",
    "IntentReceipt",
    "InterpretEvidenceOwner",
    "JobRecord",
    "JournalPublicationDelivery",
    "JournalRunInvocations",
    "JournalSemanticEvents",
    "MeasurementRequests",
    "NamespaceOperationReceipts",
    "NotApplied",
    "ObservationFactory",
    "ObservationFacts",
    "ObservationLedgerCorruptError",
    "ObservationRejectedError",
    "ObservationSubject",
    "OperationCatalog",
    "OperationEntry",
    "OperationExecutor",
    "OperationOwner",
    "OperationPorts",
    "OperationReceipts",
    "OperationRole",
    "OwnerEvent",
    "OwnerEventRejectedError",
    "Performed",
    "Performer",
    "ProductionCoreTransitions",
    "Publication",
    "PublicationAcknowledgement",
    "PublicationContext",
    "PublicationDelivery",
    "PublicationHistory",
    "ReceiptCorruptError",
    "ReceiptEvidenceLedger",
    "ReceiptStore",
    "RefusalReason",
    "RefusingRequestExecution",
    "RegisteredOperationRequests",
    "ReleasedRunInvocations",
    "RenderArtifactsOwner",
    "Replayed",
    "RequestExecutors",
    "ResolvedCoreResume",
    "ResultReceipt",
    "ResumeDiagnostic",
    "RetainRevisionOwner",
    "RootGrant",
    "RunInvocationProof",
    "RuntimeCommitError",
    "RuntimeCommitUncertainError",
    "RuntimeExecutionError",
    "RuntimeRecord",
    "RuntimeSessionRequests",
    "RuntimeWorkspaceRequests",
    "SemanticEvents",
    "SessionBinding",
    "SessionLifecycleRequests",
    "SessionRequestRouter",
    "SessionRequests",
    "SessionResolver",
    "Settled",
    "StoreWorkspaceReceipts",
    "Transient",
    "TurnDispatcher",
    "VerifyRevisionOwner",
    "WorkspaceReceipts",
    "WorkspaceRequests",
    "bind_operations",
    "build_operation_catalog",
    "commit_of",
    "owner_key",
    "production_owners",
    "receipt_executor_kinds",
    "resolve_core_resume",
    "revision_ref",
]
