"""Core runtime composition surface. No legacy loop or concrete I/O binding.

Start validates schema/declarations and persists new-epoch recovery. Inputs and
observations enter one queue; only confirmed commits authorize dispatch or
publication. Unbound executor roles return named typed refusals.
"""

from vs_runtime._core_loop import (
    CoreContractGapError,
    CoreRuntime,
    CoreRuntimeBindings,
    CoreTransitions,
    DispatchProgress,
    ObservationRejectedError,
    OwnerEventRejectedError,
    ProductionCoreTransitions,
    PublicationDelivery,
    RuntimeCommitError,
    RuntimeCommitUncertainError,
    RuntimeExecutionError,
)
from vs_runtime._core_preflight import (
    CoreResumeError,
    ResolvedCoreResume,
    ResumeDiagnostic,
    resolve_core_resume,
)
from vs_runtime._core_publications import JournalPublicationDelivery
from vs_runtime._core_record import (
    RUNTIME_SCHEMA_VERSION,
    Publication,
    PublicationAcknowledgement,
    PublicationContext,
    PublicationHistory,
    RuntimeRecord,
)
from vs_runtime._core_requests import (
    REQUEST_DISPATCH,
    EvaluationRequests,
    ExecutionContext,
    ExecutionLease,
    ExecutionOutcome,
    ExecutionResult,
    ExecutorRefusal,
    ExecutorRole,
    OperationExecutor,
    OwnerEvent,
    RefusingRequestExecution,
    RequestExecutors,
    SemanticEvents,
    SessionRequests,
    WorkspaceRequests,
    receipt_executor_kinds,
)
from vs_runtime._evaluation_requests import JobRecord, MeasurementRequests
from vs_runtime._observation_factory import (
    ObservationFactory,
    ObservationFacts,
    ObservationLedgerCorruptError,
    ObservationSubject,
)
from vs_runtime._operation_catalog import (
    Applied,
    CancellableOwner,
    Cancelled,
    Indeterminate,
    Inspection,
    NotApplied,
    OperationCatalog,
    OperationEntry,
    OperationOwner,
    RefusalReason,
)
from vs_runtime._operation_receipts import (
    IntentReceipt,
    NamespaceOperationReceipts,
    OperationReceipts,
    ResultReceipt,
)
from vs_runtime._operation_requests import RegisteredOperationRequests
from vs_runtime._receipt_store import (
    Conflict,
    Effect,
    Performed,
    ReceiptCorruptError,
    ReceiptStore,
    Refused,
    Replayed,
    Settled,
    Transient,
    owner_key,
)
from vs_runtime._render_operation import RenderArtifactsOwner
from vs_runtime._semantic_events import BlockDiagnostic, JournalSemanticEvents
from vs_runtime._verify_revision_operation import VerifyRevisionOwner
from vs_runtime._workspace_receipts import (
    AttemptBinding,
    RootGrant,
    StoreWorkspaceReceipts,
    WorkspaceReceipts,
)
from vs_runtime._workspace_requests import RuntimeWorkspaceRequests, revision_ref

__all__ = [
    "REQUEST_DISPATCH",
    "RUNTIME_SCHEMA_VERSION",
    "Applied",
    "AttemptBinding",
    "BlockDiagnostic",
    "CancellableOwner",
    "Cancelled",
    "Conflict",
    "CoreContractGapError",
    "CoreResumeError",
    "CoreRuntime",
    "CoreRuntimeBindings",
    "CoreTransitions",
    "DispatchProgress",
    "Effect",
    "EvaluationRequests",
    "ExecutionContext",
    "ExecutionLease",
    "ExecutionOutcome",
    "ExecutionResult",
    "ExecutorRefusal",
    "ExecutorRole",
    "Indeterminate",
    "Inspection",
    "IntentReceipt",
    "JobRecord",
    "JournalPublicationDelivery",
    "JournalSemanticEvents",
    "MeasurementRequests",
    "NamespaceOperationReceipts",
    "NotApplied",
    "ObservationFactory",
    "ObservationFacts",
    "ObservationLedgerCorruptError",
    "ObservationRejectedError",
    "ObservationSubject",
    "OperationCatalog",
    "OperationEntry",
    "OperationExecutor",
    "OperationOwner",
    "OperationReceipts",
    "OwnerEvent",
    "OwnerEventRejectedError",
    "Performed",
    "ProductionCoreTransitions",
    "Publication",
    "PublicationAcknowledgement",
    "PublicationContext",
    "PublicationDelivery",
    "PublicationHistory",
    "ReceiptCorruptError",
    "ReceiptCorruptError",
    "ReceiptStore",
    "RefusalReason",
    "Refused",
    "RefusingRequestExecution",
    "RegisteredOperationRequests",
    "RenderArtifactsOwner",
    "Replayed",
    "RequestExecutors",
    "ResolvedCoreResume",
    "ResultReceipt",
    "ResumeDiagnostic",
    "RootGrant",
    "RuntimeCommitError",
    "RuntimeCommitUncertainError",
    "RuntimeExecutionError",
    "RuntimeRecord",
    "RuntimeWorkspaceRequests",
    "SemanticEvents",
    "SessionRequests",
    "Settled",
    "StoreWorkspaceReceipts",
    "Transient",
    "VerifyRevisionOwner",
    "WorkspaceReceipts",
    "WorkspaceRequests",
    "owner_key",
    "receipt_executor_kinds",
    "resolve_core_resume",
    "revision_ref",
]
