"""Owned in-memory test implementations for :mod:`vs_runtime.api`."""

from vs_runtime.fakes import (
    FakeAccuracyCall,
    FakeAgentExecutionEnvironment,
    FakeAgentExecutionLifecycleSink,
    FakeAgentSession,
    FakeAgentSessions,
    FakeBenchmarkCall,
    FakeCandidateWorkspace,
    FakeCommandCall,
    FakeCommands,
    FakeControl,
    FakeEvaluation,
    FakeGitRunner,
    FakeLocalValidationCall,
    FakeModelVolumeProvisioner,
    FakeModelVolumeRequest,
    FakeProjectMaterializationEffects,
    FakeRunControlEventSink,
    FakeRunHost,
    FakeSkills,
    FakeState,
    FakeStateCommit,
    FakeTrustedShellCall,
    FakeWorkspace,
    FakeWorkspaces,
    TurnResponder,
)

__all__ = [
    "FakeAccuracyCall",
    "FakeAgentExecutionEnvironment",
    "FakeAgentExecutionLifecycleSink",
    "FakeAgentSession",
    "FakeAgentSessions",
    "FakeBenchmarkCall",
    "FakeCandidateWorkspace",
    "FakeCommandCall",
    "FakeCommands",
    "FakeControl",
    "FakeEvaluation",
    "FakeGitRunner",
    "FakeLocalValidationCall",
    "FakeModelVolumeProvisioner",
    "FakeModelVolumeRequest",
    "FakeProjectMaterializationEffects",
    "FakeRunControlEventSink",
    "FakeRunHost",
    "FakeSkills",
    "FakeState",
    "FakeStateCommit",
    "FakeTrustedShellCall",
    "FakeWorkspace",
    "FakeWorkspaces",
    "TurnResponder",
]
